#!/usr/bin/env python3
"""
test_autogenerated_caption_lang.py — an auto-transcript may not claim a
language it is not in, and a HUMAN track keeps whatever language it declares.

THE FINDING (2026-09-11). Decision 043 drops archive.org auto-ASR captions by
testing `source == "archive-asr"`. On the live catalog that predicate matches
ZERO items: archive.org names its ASR output `<file>.autogenerated.vtt` and
sets `source: "archive"`. So 1,720 auto-transcripts across 1,719 items were
never seen by that rule, and 1,334 of the 5,943 films the apps caption are
carrying one as their only source.

They are not the problem 043 described — sampled cues are clean, punctuated
English. THIRTY-FOUR of them are: they declare ar/de/it/es/ja/ru/zh/fr, and
fetching all 34 scored 33 as English-dominant text with the 34th holding one
word. A viewer who picks "Deutsch" on a French policier gets "ed / Rot / O".

The first case below is the NEGATIVE CONTROL: a human German subtitle file
must keep its German label, or this rule would quietly flatten every genuine
foreign-language track in the catalog.

Run:  python3 tools/test_autogenerated_caption_lang.py
"""

from __future__ import annotations

import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

from remediate_catalog import fix_autogenerated_caption_language  # noqa: E402

CASES = []


def check(name, got, want):
    CASES.append((name, got == want, got, want))


def item(*caps):
    return {"archiveID": "x", "captions": [dict(c) for c in caps]}


HUMAN_DE = {"lang": "de", "label": "German", "source": "subdl",
            "url": "https://example.org/sub.de.vtt"}
AUTO_DE = {"lang": "de", "label": "German", "source": "archive",
           "url": "https://archive.org/download/x/x_512kb.autogenerated.vtt"}
AUTO_EN = {"lang": "en", "label": "English", "source": "archive",
           "url": "https://archive.org/download/x/x_512kb.autogenerated.vtt"}


def main() -> int:
    # 1. THE CONTROL: a real German subtitle file is untouched.
    it = item(HUMAN_DE)
    check("control: a human German track keeps its language",
          (fix_autogenerated_caption_language([it]), it["captions"][0]["lang"]), (0, "de"))

    # 2. the finding: an auto-transcript labelled German becomes English
    it = item(AUTO_DE)
    n = fix_autogenerated_caption_language([it])
    check("an auto-transcript labelled German is relabelled", n, 1)
    check("...to English, code and label together",
          (it["captions"][0]["lang"], it["captions"][0]["label"]), ("en", "English"))

    # 3. an auto-transcript already English is left alone (no churn every build)
    it = item(AUTO_EN)
    check("an English auto-transcript is not touched", fix_autogenerated_caption_language([it]), 0)

    # 4. the TRACK IS KEPT — relabelling, never dropping. Taking captions from
    #    1,661 visible films to fix 34 would be a content decision.
    it = item(AUTO_DE)
    fix_autogenerated_caption_language([it])
    check("the track survives the fix", len(it["captions"]), 1)

    # 5. the marker is the URL, not the source string — `source` is "archive"
    #    on these, which is why Decision 043's predicate never saw them.
    it = item({"lang": "ar", "label": "Arabic", "source": "archive",
               "url": "https://archive.org/download/x/x.vtt"})
    check("a non-autogenerated archive caption is NOT relabelled",
          (fix_autogenerated_caption_language([it]), it["captions"][0]["lang"]), (0, "ar"))

    # 6. the vttURL field counts too (the published mirror the web reads)
    it = item({"lang": "ja", "label": "Japanese", "source": "archive",
               "vttURL": "https://archivewatch.org/subs/x/x.autogenerated.vtt"})
    check("the published vttURL is inspected as well as url",
          fix_autogenerated_caption_language([it]), 1)

    # 7. mixed item: only the auto track moves
    it = item(HUMAN_DE, AUTO_DE)
    fix_autogenerated_caption_language([it])
    check("a mixed item relabels only the auto track",
          [c["lang"] for c in it["captions"]], ["de", "en"])

    # 8. an item with no captions does not explode
    check("an item with no captions is a no-op",
          fix_autogenerated_caption_language([{"archiveID": "y"}]), 0)

    bad = 0
    for name, ok, got, want in CASES:
        print(("PASS " if ok else "FAIL ") + name)
        if not ok:
            bad += 1
            print(f"      got:  {got!r}\n      want: {want!r}")
    print(f"\n{len(CASES) - bad}/{len(CASES)} passed")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
